# Generated by Django 5.2.8 on 2025-12-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=200)),
                ('expertise_area', models.TextField(blank=True)),
                ('expertise_tools', models.TextField(blank=True)),
                ('manual_tools', models.TextField(blank=True)),
                ('navratnas', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
